import { z } from 'zod';
import { id, ApiError } from './security.js';
import { expandPlayerStatistics, demoPlayerMilestones } from './player-statistics.js';
const format=z.enum(['T20','ODI','TEST']);
const short=z.string().min(1).max(200);
const entityId=z.string().regex(/^[a-zA-Z0-9_-]{1,80}$/);
export const historySchema=z.object({
  profiles:z.array(z.object({id:entityId,kind:z.enum(['player','team']),name:short,team:short,biography:z.string().max(4000),careerStart:z.number().int().min(1700).max(2100),careerEnd:z.number().int().min(1700).max(2100).nullable(),statistics:z.array(z.object({format,label:short,value:z.string().min(1).max(100).nullable()}).strict()).max(300).refine(rows=>new Set(rows.map(r=>r.format+':'+r.label)).size===rows.length,{message:'Duplicate statistic label for format'}),achievements:z.array(z.object({year:z.number().int().min(1700).max(2100),title:short,description:z.string().max(1000),category:short}).strict()).max(100)}).strict()).max(500),
  rankings:z.array(z.object({category:z.enum(['team','batting','bowling','allrounder']),format,gender:z.enum(['men','women']),asOf:z.iso.date(),sourceLabel:short,entries:z.array(z.object({rank:z.number().int().positive(),entityId,name:short,team:short,rating:z.number().nonnegative().max(10000),previousRank:z.number().int().positive().nullable()}).strict()).max(100)}).strict()).max(50),
  records:z.array(z.object({format,category:short,title:short,holderName:short,profileId:entityId.nullable(),value:short,achievedOn:z.iso.date().nullable(),context:z.string().max(1000),sourceLabel:short}).strict()).max(500),
  sourceLabel:short
}).strict();
export async function importHistory(tx,providerId,raw){
  const data=historySchema.parse(raw);
  const provider=(await tx.query('SELECT * FROM providers WHERE id=$1',[providerId])).rows[0];
  if(!provider?.enabled||(providerId!=='demo'&&(!provider.license_reference||new Date(provider.license_expires_at||0)<=new Date())))throw new ApiError(403,'History license is not enabled');
  for(const p of data.profiles){const pid=`${providerId}_${p.id}`;await tx.query('INSERT INTO historical_profiles(id,provider_id,kind,name,team,biography,career_start,career_end,statistics,source_label) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,team=EXCLUDED.team,biography=EXCLUDED.biography,career_start=EXCLUDED.career_start,career_end=EXCLUDED.career_end,statistics=EXCLUDED.statistics,source_label=EXCLUDED.source_label,updated_at=now()',[pid,providerId,p.kind,p.name,p.team,p.biography,p.careerStart,p.careerEnd,JSON.stringify(p.statistics),data.sourceLabel]);await tx.query('DELETE FROM achievements WHERE profile_id=$1',[pid]);for(const a of p.achievements)await tx.query('INSERT INTO achievements(id,profile_id,year,title,description,category) VALUES($1,$2,$3,$4,$5,$6)',[id(),pid,a.year,a.title,a.description,a.category]);}
  for(const r of data.rankings){const snapshot=(await tx.query('INSERT INTO ranking_snapshots(id,provider_id,category,format,gender,as_of,source_label) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(provider_id,category,format,gender,as_of) DO UPDATE SET source_label=EXCLUDED.source_label,fetched_at=now() RETURNING id',[id(),providerId,r.category,r.format,r.gender,r.asOf,r.sourceLabel])).rows[0];await tx.query('DELETE FROM ranking_entries WHERE snapshot_id=$1',[snapshot.id]);for(const e of r.entries)await tx.query('INSERT INTO ranking_entries(snapshot_id,rank,entity_id,name,team,rating,previous_rank) VALUES($1,$2,$3,$4,$5,$6,$7)',[snapshot.id,e.rank,`${providerId}_${e.entityId}`,e.name,e.team,e.rating,e.previousRank]);}
  // Records import is a complete provider snapshot, not a delta.
  await tx.query('DELETE FROM cricket_records WHERE provider_id=$1',[providerId]);
  for(const r of data.records)await tx.query('INSERT INTO cricket_records(id,provider_id,format,category,title,holder_name,profile_id,value,achieved_on,context,source_label) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id(),providerId,r.format,r.category,r.title,r.holderName,r.profileId?`${providerId}_${r.profileId}`:null,r.value,r.achievedOn,r.context,r.sourceLabel]);
  return{profiles:data.profiles.length,rankings:data.rankings.length,records:data.records.length};
}
export function mountHistory(app,db){
  const access="p.enabled=true AND (p.id='demo' OR p.license_expires_at>now())";
  app.get('/api/rankings',async(req,res)=>{const q=z.object({format:format.default('T20'),category:z.enum(['team','batting','bowling','allrounder']).default('team'),gender:z.enum(['men','women']).default('men')}).strict().parse(req.query);const snapshot=(await db.query(`SELECT s.* FROM ranking_snapshots s JOIN providers p ON p.id=s.provider_id WHERE s.format=$1 AND s.category=$2 AND s.gender=$3 AND ${access} ORDER BY CASE WHEN p.id='demo' THEN 1 ELSE 0 END,s.as_of DESC LIMIT 1`,[q.format,q.category,q.gender])).rows[0];res.json({data:snapshot?{...snapshot,dataMode:snapshot.provider_id==='demo'?'demo':'licensed',entries:(await db.query('SELECT e.*,h.id AS profile_id FROM ranking_entries e LEFT JOIN historical_profiles h ON h.id=e.entity_id WHERE snapshot_id=$1 ORDER BY rank',[snapshot.id])).rows}:{entries:[],dataMode:'unavailable'}});});
  app.get('/api/records',async(req,res)=>{const q=z.object({format:format.optional(),category:z.enum(['batting','bowling','team']).optional()}).strict().parse(req.query);res.json({data:(await db.query(`SELECT r.*,CASE WHEN p.id='demo' THEN 'demo' ELSE 'licensed' END AS data_mode FROM cricket_records r JOIN providers p ON p.id=r.provider_id WHERE ($1::text IS NULL OR r.format=$1) AND ($2::text IS NULL OR r.category=$2) AND ${access} ORDER BY r.achieved_on DESC NULLS LAST LIMIT 100`,[q.format||null,q.category||null])).rows});});
  app.get('/api/history',async(req,res)=>{const q=z.object({kind:z.enum(['player','team']).optional(),search:z.string().max(80).default('')}).strict().parse(req.query);res.json({data:(await db.query(`SELECT h.id,h.kind,h.name,h.team,h.career_start,h.career_end,h.source_label,CASE WHEN p.id='demo' THEN 'demo' ELSE 'licensed' END AS data_mode FROM historical_profiles h JOIN providers p ON p.id=h.provider_id WHERE ($1::text IS NULL OR h.kind=$1) AND position(lower($2) in lower(h.name))>0 AND ${access} ORDER BY h.name LIMIT 100`,[q.kind||null,q.search])).rows});});
  app.get('/api/history/:id',async(req,res)=>{const profile=(await db.query(`SELECT h.*,CASE WHEN p.id='demo' THEN 'demo' ELSE 'licensed' END AS data_mode FROM historical_profiles h JOIN providers p ON p.id=h.provider_id WHERE h.id=$1 AND ${access}`,[req.params.id])).rows[0];if(!profile)throw new ApiError(404,'Profile not found');res.json({data:{...profile,statistics:profile.kind==='player'?expandPlayerStatistics(profile.statistics):profile.statistics,achievements:(await db.query('SELECT year,title,description,category FROM achievements WHERE profile_id=$1 ORDER BY year DESC',[profile.id])).rows,records:(await db.query('SELECT title,value,format,achieved_on FROM cricket_records WHERE profile_id=$1',[profile.id])).rows}});});
}
export async function seedHistory(tx){
  const source='Fictional demo data — not official rankings or records';
  const profiles=[
    {id:'arjun-mehta',kind:'player',name:'Arjun Mehta',team:'IND',biography:'A fictional top-order batter used to demonstrate career statistics, records and achievement timelines. These are not real career results.',careerStart:2016,careerEnd:null,statistics:[{format:'T20',label:'Matches',value:'84'},{format:'T20',label:'Runs',value:'2,410'},{format:'T20',label:'Strike rate',value:'143.20'},{format:'ODI',label:'Runs',value:'3,860'},{format:'TEST',label:'Runs',value:'2,150'}],achievements:[{year:2025,title:'Player of the tournament',description:'Demo Continental Cup award.',category:'award'},{year:2023,title:'First international century',description:'Fictional 112 against the Harbour XI.',category:'milestone'},{year:2016,title:'Senior debut',description:'The starting point of this sample career.',category:'debut'}]},
    {id:'maya-rao',kind:'player',name:'Maya Rao',team:'IND',biography:'A fictional all-rounder for demonstrating women’s cricket history and achievements.',careerStart:2018,careerEnd:null,statistics:[{format:'T20',label:'Matches',value:'61'},{format:'T20',label:'Wickets',value:'82'},{format:'ODI',label:'Runs',value:'1,280'},{format:'TEST',label:'Wickets',value:'24'}],achievements:[{year:2025,title:'Championship-winning performance',description:'Sample achievement for the demo league.',category:'trophy'},{year:2022,title:'First five-wicket haul',description:'Illustrative milestone, not an official record.',category:'milestone'}]},
    {id:'india-demo',kind:'team',name:'India · Demo team',team:'IND',biography:'A sample team history, deliberately separate from India’s real sporting history. Connect licensed archives for actual results.',careerStart:2000,careerEnd:null,statistics:[{format:'T20',label:'Demo wins',value:'48'},{format:'ODI',label:'Demo wins',value:'62'},{format:'TEST',label:'Demo wins',value:'31'}],achievements:[{year:2025,title:'Demo World T20 champions',description:'Fictional tournament trophy.',category:'trophy'},{year:2021,title:'Unbeaten home series',description:'Sample series milestone.',category:'series'}]}
  ];
  for(const profile of profiles)if(profile.kind==='player')profile.statistics.push(...demoPlayerMilestones(profile.id));
  const rankings=[];
  for(const f of ['T20','ODI','TEST'])for(const gender of ['men','women'])for(const category of ['team','batting','bowling','allrounder'])rankings.push({format:f,gender,category,asOf:'2026-09-16',sourceLabel:source,entries:category==='team'?[{rank:1,entityId:'india-demo',name:'India · Demo',team:'IND',rating:268,previousRank:2},{rank:2,entityId:'australia-demo',name:'Australia · Demo',team:'AUS',rating:259,previousRank:1},{rank:3,entityId:'england-demo',name:'England · Demo',team:'ENG',rating:251,previousRank:3}]:[{rank:1,entityId:gender==='women'?'maya-rao':'arjun-mehta',name:gender==='women'?'Maya Rao':'Arjun Mehta',team:'IND',rating:842,previousRank:2},{rank:2,entityId:gender==='women'?'harper-jones':'james-ellis',name:gender==='women'?'Harper Jones':'James Ellis',team:'AUS',rating:811,previousRank:1}]});
  const records=['T20','ODI','TEST'].flatMap(f=>[{format:f,category:'batting',title:'Highest individual score · Demo league',holderName:'Arjun Mehta',profileId:'arjun-mehta',value:f==='T20'?'126*':f==='ODI'?'185':'242',achievedOn:'2025-04-12',context:'Fictional demo competition. Not a world record.',sourceLabel:source},{format:f,category:'bowling',title:'Best bowling figures · Demo league',holderName:'Maya Rao',profileId:'maya-rao',value:'6/21',achievedOn:'2025-06-20',context:'Fictional figures to demonstrate the records library.',sourceLabel:source},{format:f,category:'team',title:'Longest winning streak · Demo league',holderName:'India · Demo team',profileId:'india-demo',value:'12 matches',achievedOn:'2025-08-01',context:'Sample team achievement.',sourceLabel:source}]);
  await importHistory(tx,'demo',{profiles,rankings,records,sourceLabel:source});
}
