import { createServer as httpServer } from 'node:http';
import { createServer as httpsServer } from 'node:https';
import { readFileSync } from 'node:fs';
import { createApp } from './app.js';
import { getConfig } from './config.js';
import { openDatabase } from './db.js';
const config = getConfig(), db = await openDatabase(config);
await db.query('SELECT version FROM schema_migrations LIMIT 1');
const app = createApp({ db, config });
const server = config.tlsCert && config.tlsKey ? httpsServer({ cert: readFileSync(config.tlsCert), key: readFileSync(config.tlsKey), minVersion: 'TLSv1.2' }, app) : httpServer(app);
server.requestTimeout = 15000; server.headersTimeout = 10000; server.keepAliveTimeout = 5000;
server.listen(config.port, config.host, () => console.log(`Cricket Pulse API listening on port ${config.port} (${config.databaseMode})`));
for (const signal of ['SIGINT','SIGTERM']) process.on(signal, () => { server.close(async () => { await db.close(); process.exit(0); }); setTimeout(() => process.exit(1), 10000).unref(); });
